# Generated by Django 4.2 on 2023-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('club', models.CharField(max_length=255)),
                ('distance_jump_1', models.FloatField()),
                ('distance_points_jump_1', models.FloatField()),
                ('speed_jump_1', models.FloatField()),
                ('judge_marks_a_jump_1', models.FloatField()),
                ('judge_marks_b_jump_1', models.FloatField()),
                ('judge_marks_c_jump_1', models.FloatField()),
                ('judge_marks_d_jump_1', models.FloatField()),
                ('judge_marks_e_jump_1', models.FloatField()),
                ('judge_total_points_jump_1', models.FloatField()),
                ('gate_jump_1', models.FloatField()),
                ('gate_compensation_jump_1', models.FloatField()),
                ('wind_jump_1', models.FloatField()),
                ('wind_compensation_jump_1', models.FloatField()),
                ('total_points_jump_1', models.FloatField()),
                ('ranking_jump_1', models.IntegerField()),
                ('distance_jump_2', models.FloatField()),
                ('distance_points_jump_2', models.FloatField()),
                ('speed_jump_2', models.FloatField()),
                ('judge_marks_a_jump_2', models.FloatField()),
                ('judge_marks_b_jump_2', models.FloatField()),
                ('judge_marks_c_jump_2', models.FloatField()),
                ('judge_marks_d_jump_2', models.FloatField()),
                ('judge_marks_e_jump_2', models.FloatField()),
                ('judge_total_points_jump_2', models.FloatField()),
                ('gate_jump_2', models.FloatField()),
                ('gate_compensation_jump_2', models.FloatField()),
                ('wind_jump_2', models.FloatField()),
                ('wind_compensation_jump_2', models.FloatField()),
                ('total_points_jump_2', models.FloatField()),
                ('ranking_jump_2', models.IntegerField()),
                ('total_points', models.FloatField()),
                ('team_points', models.FloatField()),
                ('team_ranking', models.IntegerField()),
            ],
        ),
    ]
