# Generated by Django 4.2 on 2023-04-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0003_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post',
            new_name='content',
        ),
    ]
