# Generated by Django 4.2 on 2023-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0006_alter_jumper_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jumper',
        ),
        migrations.DeleteModel(
            name='TournamentFile',
        ),
    ]
